version: '3.8'

services:

  mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234b
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234b
    ports:
      - "3307:3306"  # Expor a porta 3306 para 3307 na máquina host
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Adicionar script de inicialização
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_USERNAME: admin
      MYSQL_PASSWORD: 1234b
      MYSQL_DB_NAME: shorturl
      MYSQL_DB_HOST: mysql
      MYSQL_DB_PORT: 3306  # Conectar na porta interna 3306
    ports:
      - "3333:3333"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mysql-data:
