version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shorturl
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234b
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: dev
      MYSQL_USERNAME: admin
      MYSQL_PASSWORD: 1234b
      MYSQL_DB_NAME: shorturl
      MYSQL_DB_HOST: db
      MYSQL_DB_PORT: 3306
    depends_on:
      - db

volumes:
  db_data:
